### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by GCPanic** [freedom-introvert/biliSendCommAntifraud#13]
系统：MIUI 14.0.21
使用方式：直接使用
测试视频：BV1RP411B7C1
测试评论：`如来？弱智！`
系统提供的Trace：
```
java.lang.StringIndexOutOfBoundsException: begin 8, end 40, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at icu.freedomIntrovert.biliSendCommAntifraud.comment.CommentManipulator.getCsrfFromCookie(CommentManipulator.java:57)
	at icu.freedomIntrovert.biliSendCommAntifraud.comment.CommentManipulator.sendComment(CommentManipulator.java:134)
	at icu.freedomIntrovert.biliSendCommAntifraud.MainActivity$2.onMatchedArea(MainActivity.java:197)
	at icu.freedomIntrovert.biliSendCommAntifraud.comment.presenters.CommentPresenter.lambda$matchToArea$0(CommentPresenter.java:54)
	at icu.freedomIntrovert.biliSendCommAntifraud.comment.presenters.CommentPresenter$$ExternalSyntheticLambda3.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8235)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
// 第一次测试就直接崩溃了......

**Comment by Xx114514xX1819** [comment]
疑似你自身原因，请提供B站版本

**Comment by p88oo** [comment]
我是7.30.0的版本，有些评论检测完了之后不弹检测结果就闪退被返回到app主页了，概率好像还挺高，这种是不是等于评论被屏蔽了

**Comment by freedom-introvert** [comment]
好像是你cookie有问题

**Comment by p88oo** [comment]
我清除数据重新获取cookie还是会出现部分评论不返回结果直接闪退回到主页
