### ISSUE TITLE
在仅安装国际版 bilibili 的环境下使用定位评论功能时应用异常退出

### ISSUE THREAD

**Issue by UraraChiya** [freedom-introvert/biliSendCommAntifraud#52]
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {tv.danmaku.bili/tv.danmaku.bili.MainActivityV2}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2184)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1831)
	at android.app.Activity.startActivityForResult(Activity.java:5580)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5533)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:6036)
	at android.app.Activity.startActivity(Activity.java:6003)
	at icu.freedomIntrovert.biliSendCommAntifraud.CommentLocator.lunch(Unknown Source:313)
	at icu.freedomIntrovert.biliSendCommAntifraud.HistoryCommentAdapter.lambda$showSubMenu$9(Unknown Source:14)
	at icu.freedomIntrovert.biliSendCommAntifraud.HistoryCommentAdapter.$r8$lambda$1S1bbxq4cs51R6ZNGf7DP2SDgJo(SourceFile:1)
	at icu.freedomIntrovert.biliSendCommAntifraud.HistoryCommentAdapter$$ExternalSyntheticLambda5.onMenuItemClick(SourceFile:1)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1209)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3226)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4224)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3955)
	at android.widget.DropDownListView.onTouchEvent(DropDownListView.java:116)
	at android.view.View.dispatchTouchEvent(View.java:15121)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3165)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2833)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2590)
	at android.view.View.dispatchPointerEvent(View.java:15398)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6978)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6735)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6248)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6209)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6379)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6217)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6436)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6190)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6248)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6209)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6217)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6190)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9385)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9336)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9290)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9536)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:261)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9477)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9630)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:434)
	at android.view.Choreographer.doFrame(Choreographer.java:918)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by freedom-introvert** [comment]
😂

**Comment by UraraChiya** [comment]
试着更换了5.9.9版本的模块，使用此功能不会闪退了，但是只会跳转到屄站首页，bilibili版本是3.18.2，系统是ColorOS13.1

**Comment by UraraChiya** [comment]
哦，现在好像正常了，之前应该是我没有重启屄站导致的

**Comment by freedom-introvert** [comment]
屄站？好家伙，你有多恨b站啊😂。或者是不是主页总是被推送卖淫小孩🤢
